spring:
  application:
    name: demo2-api-gateway

  cloud:
      config:
        uri:  http://localhost:9200
        name: cloud-config
        profile: gateway
#server:
#  port: 9300
#指定Eureka的注册地址（通过此地址进行服务的注册）
eureka:
  client:
    serviceUrl:
#    服务中心地址
      defaultZone: http://localhost:9100/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10

#zuul路由功能(若建立了配置服务，可以在配置服务中心定义)
#zuul:
#  routes:
#    service1:
#      path: /service1/**
#      serviceId: common-service1
#    service2:
#      path: /service2/**
#      serviceId: common-service2